from constants import MAZE_WIDTH, MAZE_DIMENSION, BORDER_SIZE

# AGENT CONSTANTS #
START_X = (MAZE_WIDTH - 2 * BORDER_SIZE) / MAZE_DIMENSION / 2 + BORDER_SIZE
START_Y = (MAZE_WIDTH - 2 * BORDER_SIZE) / MAZE_DIMENSION / 2 + BORDER_SIZE
