from src.constants import MAZE_WIDTH, MAZE_DIMENSION, BORDER_SIZE, WALL_WIDTH

# BACTERIA SIMULATION #
NUMBER_BACTERIA = 1
TUMBLE_DIRECTION_CHANGE_SPLIT = 5

# BIOLOGICAL DIMENSIONS #
AVG_BACTERIA_RADIUS = 1 # microns
CHANNEL_WIDTH = 3 # microns
CHANNEL_WIDTH_PX = (MAZE_WIDTH - 2 * BORDER_SIZE) / MAZE_DIMENSION - WALL_WIDTH
BACTERIA_RADIUS_PX = AVG_BACTERIA_RADIUS * CHANNEL_WIDTH_PX / CHANNEL_WIDTH