import math

from src.constants import PIXEL_UM_RATIO

# BACTERIA SIMULATION #
NUMBER_BACTERIA = 50
TUMBLE_DIRECTION_CHANGE_SPLIT = 5

# BIOLOGICAL DIMENSIONS #
AVG_BACTERIA_RADIUS = 1  # microns
BACTERIA_RADIUS_PX = AVG_BACTERIA_RADIUS * PIXEL_UM_RATIO

# E. COLI #
E_COLI_RUN_TIME = 0.81  # s
E_COLI_RUN_TIME_UNCERTAINTY = 0.7  # s
E_COLI_TUMBLE_TIME = 0.14  # s
E_COLI_TUMBLE_TIME_UNCERTAINTY = 0.01  # s
E_COLI_RUN_VELOCITY = 11.4  # um/s
E_COLI_RUN_VELOCITY_UNCERTAINTY = 3.4  # um/s
E_COLI_ANGULAR_VELOCITY = math.radians(38 / E_COLI_TUMBLE_TIME)
E_COLI_ANGULAR_VELOCITY_UNCERTAINTY = math.radians(25 / E_COLI_TUMBLE_TIME)
E_COLI_TUMBLE_VELOCITY = E_COLI_RUN_VELOCITY / 5
E_COLI_TUMBLE_VELOCITY_UNCERTAINTY = E_COLI_RUN_VELOCITY_UNCERTAINTY / 5

# M. Marinus #
M_MAR_RUN_TIME = 0.6  # s
M_MAR_RUN_TIME_UNCERTAINTY = 0.2  # s
M_MAR_TUMBLE_TIME = M_MAR_RUN_TIME / 0.74 * 0.26  # s
M_MAR_TUMBLE_TIME_UNCERTAINTY = M_MAR_RUN_TIME_UNCERTAINTY / 0.74 * 0.26  # s
M_MAR_RUN_VELOCITY = 100  # um/s
M_MAR_RUN_VELOCITY_UNCERTAINTY = 15  # um/s
M_MAR_TUMBLE_VELOCITY = M_MAR_RUN_VELOCITY / 5
M_MAR_TUMBLE_VELOCITY_UNCERTAINTY = M_MAR_RUN_VELOCITY_UNCERTAINTY / 5
M_MAR_ANGULAR_VELOCITY = math.radians(360)
M_MAR_ANGULAR_VELOCITY_UNCERTAINTY = math.radians(30)


# Run Time #
SIMULATION_TIME = 20 * 60  # 20 min