# GUI DIMENSIONS #
BORDER_SIZE = 5
PANEL_HEIGHT = 500
MAZE_WIDTH = 500

# CONTROL PANEL DIMENSIONS #
CONTROL_PANEL_WIDTH = 700
OPTIONS_INTERFACE_HEIGHT = 300
INFO_INTERFACE_HEIGHT = 200
PANEL_BORDER = 2
BUTTON_WIDTH = 10

# CONTROL PANEL OPTIONS #
MAZE_TYPE = "Maze"
RANDOM_MAZE = "Random"
SINGLE_PATH_MAZE = "Single Path"
MULTI_PATH_MAZE = "Multi Path"
MAZE_OPTIONS = [RANDOM_MAZE, SINGLE_PATH_MAZE, MULTI_PATH_MAZE]

RUN_TYPE = "Simulation"
BACTERIA_SIMULATION = "Bacteria"
RANDOM_WALK_SIMULATION = "Random Walk"
WALL_FOLLOW_SIMULATION = "Wall Follow"
RUN_OPTIONS = [BACTERIA_SIMULATION, RANDOM_WALK_SIMULATION, WALL_FOLLOW_SIMULATION]

BACTERIA_TYPE = "Bacteria"
ECOLI_TYPE = "E. coli"
MARINUS_TYPE = "M. marinus"
BACTERIA_OPTIONS = [ECOLI_TYPE, MARINUS_TYPE]

RUN_VELOCITY = "Run Velocity (nm/s)"
TUMBLE_VELOCITY = "Tumble Velocity (nm/s)"
WALL_BOUNCE = "Wall Bounce (rad)"
RUN_TIME = "Run Time (s)"
TUMBLE_TIME = "Tumble Time (s)"
TUMBLE_ANGULAR_VELOCITY = "Angular Velocity (rad/s)"

RUN_SIMULATION = "Run"
FLOOD_FILL = "BFS"
CHANGE_MAZE = "Change Maze"

# MAZE CONSTANTS #
MAZE_DIMENSION = 20
WALL_WIDTH = 2

# GUI FPS #
FPS = 60
